version: '3'
services:
  cubeauditsse:
    image: analyticsearth/cubeauditsse
    deploy:
      mode: global
    ports:
      - "50055:50055/tcp"
    volumes:
      - filelog:/data/cube  

volumes:
  filelog: